### ISSUE TITLE
Reconnecting client to server

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/at-home-refbox#4]
In case of a lost connection, the clients don't automatically reconnect. This would be desirable (although I can imagine that this is more a development problem than a problem in practice where the server should always be up-and-running.

**Comment by MatthijsBurgh** [comment]
~~Solution: https://stackoverflow.com/a/23176223/12135039~~

~~Apply to https://github.com/tue-robotics/at-home-refbox/blob/master/refbox/src/refBox.js#L184~~
